name: Semgrep Scan

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  semgrep:
    name: Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install Semgrep OSS
        run: pip install semgrep
      - name: Ensure Semgrep OSS is installed
        run: |
          if ! command -v semgrep &> /dev/null; then
            echo "::error::Semgrep OSS CLI is not installed."
            exit 1
          fi
          semgrep --version
      - name: Run Semgrep
        run: semgrep scan --config auto
